services:
  apache:
    build: .
    image: 'php-8-apache-mc'
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    
  db:
    image: mysql
    container_name: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./assets/data:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db
